[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Set minimum thresholds for each report area
[plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    seo = 0.9
    best-practices = 0.9
    pwa = 0
  
# Set the plugin to run prior to deploy, failing the build if minimum thresholds aren't set 
[plugins.inputs]
  fail_deploy_on_score_thresholds = "true"

# you can specify thresholds per audit
[plugins.inputs.audits.thresholds]
  performance = 0.8